### ISSUE TITLE
[BUG] building from source on alpine linux 3.14.2 x8_64

### ISSUE THREAD

**Issue by truatpasteurdotfr** [aristocratos/btop#13]
**Describe the bug**

Building failing on Alpine linux 3.14.2 x86_64

**To Reproduce**

- curl -L https://github.com/aristocratos/btop/archive/refs/tags/v1.0.2.tar.gz| tar xzvf -
- cd btop-1.0.2/
- make

```
Linux alpine 4.9.65-1-hardened #2-Alpine SMP Mon Nov 27 15:36:10 GMT 2017 x86_64 GNU/Linux
alpine:~$ more /etc/alpine-release 
3.14.2
alpine:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-alpine-linux-musl/10.3.1/lto-wrapper
Target: x86_64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-10.3.1_git20210424/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl --target=x86_64-alpine-linux-musl --with-pkgversion='Alpine 10.3.1_git20210424' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
alpine:~$ 
```

**Expected behavior**

building without errors

**Screenshots**

```
alpine:~/btop-1.0.2$ make
 
 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.2
PLATFORM   ?| Linux
ARCH       ?| x86_64
CXX        ?| g++ (10.3.1)
THREADS    :| auto
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=auto
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.2)
<...>
Linking and optimizing binary...
/usr/include/c++/10.3.1/ext/string_conversions.h: In function '__to_xstring.constprop':
/usr/include/fortify/stdio.h:70:28: error: inlining failed in call to 'always_inline' 'vsnprintf': function body can be overwritten at link time
   70 | _FORTIFY_FN(vsnprintf) int vsnprintf(char *__s, size_t __n, const char *__f,
      |                            ^
/usr/include/c++/10.3.1/ext/string_conversions.h:111:32: note: called from here
  111 |       const int __len = __convf(__s, __n, __fmt, __args);
      |                                ^
make[1]: *** [/tmp/ccLbJlLP.mk:56: /tmp/btop.OglgLe.ltrans18.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:167: btop] Error 1

```

**Comment by truatpasteurdotfr** [comment]
```
alpine:~/btop-1.0.2$ make LDCXXFLAGS="-pthread -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection" 
 
 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.2
PLATFORM   ?| Linux
ARCH       ?| x86_64
CXX        ?| g++ (10.3.1)
THREADS    :| auto
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=auto
LDCXXFLAGS :| -pthread -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.2)

Linking and optimizing binary...
/usr/include/c++/10.3.1/ext/string_conversions.h: In function '__to_xstring.constprop':
/usr/include/fortify/stdio.h:70:28: error: inlining failed in call to 'always_inline' 'vsnprintf': function body can be overwritten at link time
   70 | _FORTIFY_FN(vsnprintf) int vsnprintf(char *__s, size_t __n, const char *__f,
      |                            ^
/usr/include/c++/10.3.1/ext/string_conversions.h:111:32: note: called from here
  111 |       const int __len = __convf(__s, __n, __fmt, __args);
      |                                ^
make[1]: *** [/tmp/ccdfcncf.mk:56: /tmp/btop.dfBpdb.ltrans18.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:167: btop] Error 1
alpine:~/btop-1.0.2$ 
```

**Comment by aristocratos** [comment]
@truatpasteurdotfr 
Works fine with gcc 10.3.0 on Ubuntu 21.04.

Looks like it's a compiler bug (specific to Alpine?) https://gitlab.alpinelinux.org/alpine/aports/-/issues/8626

Try `make LDCXXFLAGS="-pthread -U_FORTIFY_SOURCE -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection"`

If that doesn't work, then `make OPTFLAGS=-O2 -ftree-loop-vectorize` hopefully should.

**Comment by truatpasteurdotfr** [comment]
```
alpine:~/btop-1.0.2$ make LDCXXFLAGS="-pthread -U_FORTIFY_SOURCE -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection"
 
 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.2
PLATFORM   ?| Linux
ARCH       ?| x86_64
CXX        ?| g++ (10.3.1)
THREADS    :| auto
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=auto
LDCXXFLAGS :| -pthread -U_FORTIFY_SOURCE -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.2)

Linking and optimizing binary...
/usr/include/c++/10.3.1/ext/string_conversions.h: In function '__to_xstring.constprop':
/usr/include/fortify/stdio.h:70:28: error: inlining failed in call to 'always_inline' 'vsnprintf': function body can be overwritten at link time
   70 | _FORTIFY_FN(vsnprintf) int vsnprintf(char *__s, size_t __n, const char *__f,
      |                            ^
/usr/include/c++/10.3.1/ext/string_conversions.h:111:32: note: called from here
  111 |       const int __len = __convf(__s, __n, __fmt, __args);
      |                                ^
make[1]: *** [/tmp/ccBCJHba.mk:56: /tmp/btop.DMCndD.ltrans18.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:167: btop] Error 1
alpine:~/btop-1.0.2$ 
```
```
alpine:~/btop-1.0.2$ make OPTFLAGS="-O2 -ftree-loop-vectorize"
 
 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.2
PLATFORM   ?| Linux
ARCH       ?| x86_64
CXX        ?| g++ (10.3.1)
THREADS    :| auto
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize
LDCXXFLAGS :| -pthread -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.2)

Linking and optimizing binary...
/usr/include/c++/10.3.1/ext/string_conversions.h: In function '__to_xstring.constprop':
/usr/include/fortify/stdio.h:70:28: error: inlining failed in call to 'always_inline' 'vsnprintf': function body can be overwritten at link time
   70 | _FORTIFY_FN(vsnprintf) int vsnprintf(char *__s, size_t __n, const char *__f,
      |                            ^
/usr/include/c++/10.3.1/ext/string_conversions.h:111:32: note: called from here
  111 |       const int __len = __convf(__s, __n, __fmt, __args);
      |                                ^
lto-wrapper: fatal error: g++ returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:167: btop] Error 1
alpine:~/btop-1.0.2$ 
```

**Comment by aristocratos** [comment]
@truatpasteurdotfr 
You can try `make OPTFLAGS=-O1` and `make OPTFLAGS=-O0`
But you're probably better off downloading and running the precompiled binaries if any of those work since you will be disabling the optimizations and making it slow.

**Comment by truatpasteurdotfr** [comment]
```
alpine:~/btop-1.0.5$ make LDCXXFLAGS="-pthread -U_FORTIFY_SOURCE -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection"
 
 ██████╗ ████████╗ ██████╗ ██████╗
 ██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗   ██╗    ██╗
 ██████╔╝   ██║   ██║   ██║██████╔╝ ██████╗██████╗
 ██╔══██╗   ██║   ██║   ██║██╔═══╝  ╚═██╔═╝╚═██╔═╝
 ██████╔╝   ██║   ╚██████╔╝██║        ╚═╝    ╚═╝
 ╚═════╝    ╚═╝    ╚═════╝ ╚═╝      Makefile v1.2
PLATFORM   ?| Linux
ARCH       ?| x86_64
CXX        ?| g++ (10.3.1)
THREADS    :| auto
REQFLAGS   !| -std=c++20
WARNFLAGS  :| -Wall -Wextra -pedantic
OPTFLAGS   :| -O2 -ftree-loop-vectorize -flto=auto
LDCXXFLAGS :| -pthread -U_FORTIFY_SOURCE -D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector -fstack-clash-protection -fcf-protection
CXXFLAGS   +| $(REQFLAGS) $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)
LDFLAGS    +| $(LDCXXFLAGS) $(OPTFLAGS) $(WARNFLAGS)

Building btop++ (v1.0.5)
Compiling src/btop.cpp
-> obj/btop.o                      (2.2MiB) (10s)
Compiling src/btop_config.cpp
-> obj/btop_config.o               (1.4MiB) (08s)
Compiling src/btop_draw.cpp
-> obj/btop_draw.o                 (2.2MiB) (11s)
Compiling src/btop_input.cpp
-> obj/btop_input.o                (1.4MiB) (08s)
Compiling src/btop_menu.cpp
-> obj/btop_menu.o                 (2.0MiB) (09s)
Compiling src/btop_theme.cpp
-> obj/btop_theme.o                (1.4MiB) (07s)
Compiling src/btop_tools.cpp
-> obj/btop_tools.o                (1.3MiB) (10s)
Compiling src/linux/btop_collect.cpp
-> obj/linux/btop_collect.o        (2.9MiB) (15s)

Linking and optimizing binary...
-> bin/btop                        (1.4MiB) (01m:00s)

Build complete in (02m:19s)
```
yeah! maybe the previous rebuilds were missing a `make clean` before changing the LDCXXFLAGS option!

safety for alpine in the way but that's another story...
```
alpine:~/btop-1.0.5$ ./bin/btop 
ERROR: Exception in Shared::init() -> filesystem error: status: Permission denied [/sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq]
```

**Comment by truatpasteurdotfr** [comment]
for what is is worth, the x86_64 statically built and stripped weights only 1.8MB and runs out of the box on an EOL'ed CentOS-6 
kernel ( 2.6.32-754.x kernel) !.
